openapi: 3.0.3
info:
  title: Authentication & User APIs
  description: APIs for handling user authentication and user-related actions.
  version: 1.0.0
paths:
  /api/public/auth/signup:
    post:
      tags:
        - Authentication
      summary: User signup
      description: Create a new user account.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                  description: User's email address.
                  example: user@example.com
                password:
                  type: string
                  format: password
                  description: User's password.
                  example: mySecurePassword123
                name:
                  type: string
                  description: User's full name.
                  example: John Doe
                recall:
                  type: boolean
                  description: Remember the user for auto signin.
                  example: true
              required:
                - email
                - password
                - name
      responses:
        '201':
          description: User created successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: User signed up successfully
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                        description: Unique user ID.
                        example: cm6c6pwmr0000rx3rbtzyohvx
                      email:
                        type: string
                        format: email
                        example: user@example.com
                      name:
                        type: string
                        example: John Doe
                      image:
                        type: string
                        nullable: true
                        example: null
                      createdAt:
                        type: string
                        format: date-time
                        example: 2025-01-25T12:46:24.627Z
                      accessToken:
                        type: string
                        description: JWT access token.
                        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...

  /api/public/auth/signin:
    post:
      tags:
        - Authentication
      summary: User signin
      description: Authenticate a user with their email and password.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                  description: User's email address.
                  example: user@example.com
                password:
                  type: string
                  format: password
                  description: User's password.
                  example: mySecurePassword123
                recall:
                  type: boolean
                  description: Remember the user for auto signin.
                  example: true
              required:
                - email
                - password
      responses:
        '200':
          description: User authenticated successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: User signed in successfully
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                        description: Unique user ID.
                        example: cm6c6pwmr0000rx3rbtzyohvx
                      email:
                        type: string
                        format: email
                        example: user@example.com
                      name:
                        type: string
                        example: John Doe
                      image:
                        type: string
                        nullable: true
                        example: null
                      createdAt:
                        type: string
                        format: date-time
                        example: 2025-01-25T12:46:24.627Z
                      accessToken:
                        type: string
                        description: JWT access token.
                        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...

  /api/public/auth/refresh:
    get:
      tags:
        - Authentication
      summary: Refresh tokens
      description: Refresh the user's authentication tokens.
      responses:
        '200':
          description: Tokens refreshed successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Tokens refreshed successfully
                  data:
                    type: object
                    properties:
                      accessToken:
                        type: string
                        description: JWT access token.
                        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...

  /api/private/user/me:
    get:
      tags:
        - User
      summary: Get the currently authenticated user's details
      description: Retrieve details of the authenticated user, excluding the access token.
      responses:
        '200':
          description: User details retrieved successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: User details retrieved successfully
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                        description: Unique user ID.
                        example: cm6c6pwmr0000rx3rbtzyohvx
                      email:
                        type: string
                        format: email
                        example: user@example.com
                      name:
                        type: string
                        example: John Doe
                      image:
                        type: string
                        nullable: true
                        example: null
                      createdAt:
                        type: string
                        format: date-time
                        example: 2025-01-25T12:46:24.627Z

  /api/private/user/signout:
    get:
      tags:
        - User
      summary: User signout
      description: Sign out the currently authenticated user.
      responses:
        '200':
          description: User signed out successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Sign out successfully

  /api/private/user/chats:
    get:
      tags:
        - User
      summary: Retrieve user chats
      description: Get a list of chats associated with the authenticated user.
      responses:
        '200':
          description: User chats retrieved successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: User chats retrieved successfully
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          description: Chat ID.
                          example: cm6cbvzyt0001rxkcxbrg4l6q
                        name:
                          type: string
                          description: Chat name.
                          example: Roadmap to Becoming a Software Engineer
                        createdAt:
                          type: string
                          format: date-time
                          description: When the chat was created.
                          example: 2025-01-25T15:11:06.966Z
