openapi: 3.0.0
info:
  title: Neo Codex AI API
  description: This is the API documentation for the Neo Codex AI backend.
  version: 1.0.0
servers:
  - url: http://localhost:1611
    description: Local server
paths: